apiVersion: v1
kind: ConfigMap
metadata:
  name: nssf-configmap
  labels:
    app.kubernetes.io/version: "v4.0.1"
    app: free5gc
data:
  nssfcfg.yaml: |
    info:
      version: 1.0.2
      description: NSSF initial local configuration

    configuration:
      serviceNameList:
        - nnssf-nsselection
        - nnssf-nssaiavailability

      sbi:
        scheme: http
        registerIPv4: nssf-nnssf  # IP used to register to NRF
        bindingIPv4: 0.0.0.0      # IP used to bind the service
        port: 80
        tls:
          key: config/nssf.key
          pem: config/nssf.pem
      
      nrfUri: http://nrf-nnrf:8000
      nrfCertPem: cert/nrf.pem
      
      nsiList:
        - snssai:
            sst: 1
          nsiInformationList:
            - nrfId: http://nrf-nnrf:8000/nnrf-nfm/v1/nf-instances
              nsiId: 10
        - snssai:
            sst: 1
            sd: 000001
          nsiInformationList:
            - nrfId: http://nrf-nnrf:8000/nnrf-nfm/v1/nf-instances
              nsiId: 11
        - snssai:
            sst: 1
            sd: 000002
          nsiInformationList:
            - nrfId: http://nrf-nnrf:8000/nnrf-nfm/v1/nf-instances
              nsiId: 12
        - snssai:
            sst: 1
            sd: 000003
          nsiInformationList:
            - nrfId: http://nrf-nnrf:8000/nnrf-nfm/v1/nf-instances
              nsiId: 13
        - snssai:
            sst: 1
            sd: 000004
          nsiInformationList:
            - nrfId: http://nrf-nnrf:8000/nnrf-nfm/v1/nf-instances
              nsiId: 14
        - snssai:
            sst: 1
            sd: 000005
          nsiInformationList:
            - nrfId: http://nrf-nnrf:8000/nnrf-nfm/v1/nf-instances
              nsiId: 15
        - snssai:
            sst: 1
            sd: 000006
          nsiInformationList:
            - nrfId: http://nrf-nnrf:8000/nnrf-nfm/v1/nf-instances
              nsiId: 16
        - snssai:
            sst: 1
            sd: 000007
          nsiInformationList:
            - nrfId: http://nrf-nnrf:8000/nnrf-nfm/v1/nf-instances
              nsiId: 17
        - snssai:
            sst: 1
            sd: 000008
          nsiInformationList:
            - nrfId: http://nrf-nnrf:8000/nnrf-nfm/v1/nf-instances
              nsiId: 18
        - snssai:
            sst: 1
            sd: 000009
          nsiInformationList:
            - nrfId: http://nrf-nnrf:8000/nnrf-nfm/v1/nf-instances
              nsiId: 19
        - snssai:
            sst: 1
            sd: 010203
          nsiInformationList:
            - nrfId: http://nrf-nnrf:8000/nnrf-nfm/v1/nf-instances
              nsiId: 22
      amfSetList:
        - amfSetId: 1
          amfList:
            - ffa2e8d7-3275-49c7-8631-6af1df1d9d26
            - 0e8831c3-6286-4689-ab27-1e2161e15cb1
            - a1fba9ba-2e39-4e22-9c74-f749da571d0d
          nrfAmfSet: http://nrf-nnrf:8081/nnrf-nfm/v1/nf-instances
          supportedNssaiAvailabilityData:
            - tai:
                plmnId:
                  mcc: 466
                  mnc: 92
                tac: 33456
              supportedSnssaiList:
                - sst: 1
                  sd: 1
                - sst: 1
                  sd: 2
                - sst: 2
                  sd: 1
            - tai:
                plmnId:
                  mcc: 466
                  mnc: 92
                tac: 33457
              supportedSnssaiList:
                - sst: 1
                - sst: 1
                  sd: 1
                - sst: 1
                  sd: 2
        - amfSetId: 2
          nrfAmfSet: http://nrf-nnrf:8084/nnrf-nfm/v1/nf-instances
          supportedNssaiAvailabilityData:
            - tai:
                plmnId:
                  mcc: 466
                  mnc: 92
                tac: 33456
              supportedSnssaiList:
                - sst: 1
                - sst: 1
                  sd: 1
                - sst: 1
                  sd: 3
                - sst: 2
                  sd: 1
            - tai:
                plmnId:
                  mcc: 466
                  mnc: 92
                tac: 33458
              supportedSnssaiList:
                - sst: 1
                - sst: 1
                  sd: 1
                - sst: 2
      nssfName: NSSF
      supportedPlmnList:
        - mcc: 208
          mnc: 93
      supportedNssaiInPlmnList:
        - plmnId:
            mcc: 208
            mnc: 93
          supportedSnssaiList:
            - sst: 1
              sd: 010203
            - sst: 1
              sd: 000001
            - sst: 1
              sd: 000002
            - sst: 1
              sd: 000003
            - sst: 1
              sd: 000004
            - sst: 1
              sd: 000005
            - sst: 1
              sd: 000006
            - sst: 1
              sd: 000007
            - sst: 1
              sd: 000008
            - sst: 1
              sd: 000009
            - sst: 1
              sd: 000010    
      amfList:
        - nfId: 469de254-2fe5-4ca0-8381-af3f500af77c
          supportedNssaiAvailabilityData:
            - tai:
                plmnId:
                  mcc: 466
                  mnc: 92
                tac: 33456
              supportedSnssaiList:
                - sst: 1
                - sst: 1
                  sd: 2
                - sst: 2
            - tai:
                plmnId:
                  mcc: 466
                  mnc: 92
                tac: 33457
              supportedSnssaiList:
                - sst: 1
                  sd: 1
                - sst: 1
                  sd: 2
        - nfId: fbe604a8-27b2-417e-bd7c-8a7be2691f8d
          supportedNssaiAvailabilityData:
            - tai:
                plmnId:
                  mcc: 466
                  mnc: 92
                tac: 33458
              supportedSnssaiList:
                - sst: 1
                - sst: 1
                  sd: 1
                - sst: 1
                  sd: 3
                - sst: 2
            - tai:
                plmnId:
                  mcc: 466
                  mnc: 92
                tac: 33459
              supportedSnssaiList:
                - sst: 1
                - sst: 1
                  sd: 1
                - sst: 2
                - sst: 2
                  sd: 1
        - nfId: b9e6e2cb-5ce8-4cb6-9173-a266dd9a2f0c
          supportedNssaiAvailabilityData:
            - tai:
                plmnId:
                  mcc: 466
                  mnc: 92
                tac: 33456
              supportedSnssaiList:
                - sst: 1
                - sst: 1
                  sd: 1
                - sst: 1
                  sd: 2
                - sst: 2
            - tai:
                plmnId:
                  mcc: 466
                  mnc: 92
                tac: 33458
              supportedSnssaiList:
                - sst: 1
                - sst: 1
                  sd: 1
                - sst: 2
                - sst: 2
                  sd: 1
      taList:
        - tai:
            plmnId:
              mcc: 466
              mnc: 92
            tac: 33456
          accessType: 3GPP_ACCESS
          supportedSnssaiList:
            - sst: 1
            - sst: 1
              sd: 1
            - sst: 1
              sd: 2
            - sst: 2
        - tai:
            plmnId:
              mcc: 466
              mnc: 92
            tac: 33457
          accessType: 3GPP_ACCESS
          supportedSnssaiList:
            - sst: 1
            - sst: 1
              sd: 1
            - sst: 1
              sd: 2
            - sst: 2
        - tai:
            plmnId:
              mcc: 466
              mnc: 92
            tac: 33458
          accessType: 3GPP_ACCESS
          supportedSnssaiList:
            - sst: 1
            - sst: 1
              sd: 1
            - sst: 1
              sd: 3
            - sst: 2
          restrictedSnssaiList:
            - homePlmnId:
                mcc: 310
                mnc: 560
              sNssaiList:
                - sst: 1
                  sd: 3
        - tai:
            plmnId:
              mcc: 466
              mnc: 92
            tac: 33459
          accessType: 3GPP_ACCESS
          supportedSnssaiList:
            - sst: 1
            - sst: 1
              sd: 1
            - sst: 2
            - sst: 2
              sd: 1
          restrictedSnssaiList:
            - homePlmnId:
                mcc: 310
                mnc: 560
              sNssaiList:
                - sst: 2
                  sd: 1
      mappingListFromPlmn:
        - operatorName: NTT Docomo
          homePlmnId:
            mcc: 440
            mnc: 10
          mappingOfSnssai:
            - servingSnssai:
                sst: 1
                sd: 1
              homeSnssai:
                sst: 1
                sd: 1
            - servingSnssai:
                sst: 1
                sd: 2
              homeSnssai:
                sst: 1
                sd: 3
            - servingSnssai:
                sst: 1
                sd: 3
              homeSnssai:
                sst: 1
                sd: 4
            - servingSnssai:
                sst: 2
                sd: 1
              homeSnssai:
                sst: 2
                sd: 2
        - operatorName: AT&T Mobility
          homePlmnId:
            mcc: 310
            mnc: 560
          mappingOfSnssai:
            - servingSnssai:
                sst: 1
                sd: 1
              homeSnssai:
                sst: 1
                sd: 2
            - servingSnssai:
                sst: 1
                sd: 2
              homeSnssai:
                sst: 1
                sd: 3      

    logger:
      enable: true
      level: info
      reportCaller: false
