apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cert-pvc
  labels:
    project: free5gc
spec:
  selector:
    matchLabels:
      project: free5gc
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 1Mi
