---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nrf-configmap
  labels:
    app.kubernetes.io/version: "v4.0.1"
    app: free5gc
data:
  nrfcfg.yaml: |
    info:
      version: 1.0.2
      description: NRF initial local configuration

    configuration:
      MongoDBName: free5gc
      MongoDBUrl: mongodb://mongodb:27017

      serviceNameList:
        - nnrf-nfm
        - nnrf-disc

      sbi:
        scheme: http
        registerIPv4: nrf-nnrf  # IP used to serve NFs or register to another NRF
        bindingIPv4: 0.0.0.0    # IP used to bind the service
        port: 8000
        cert:
          pem: config/nrf.pem
          key: config/nrf.key
        rootCert:
          pem: config/root.pem
          key: config/root.key
      DefaultPlmnId:
        mcc: 208
        mnc: 93

    logger:
      enable: true
      level: info
      reportCaller: false
