---
apiVersion: v1
kind: ConfigMap
metadata:
  name: udr-configmap
  labels:
    app.kubernetes.io/version: "v4.0.1"
    app: free5gc
data:
  udrcfg.yaml: |
    info:
      version: 1.1.0
      description: UDR initial local configuration

    configuration:
      sbi:
        scheme: http
        registerIPv4: udr-nudr # IP used to register to NRF
        bindingIPv4: 0.0.0.0  # IP used to bind the service
        port: 80
        tls:
          key: config/udr.key
          pem: config/udr.pem

      dbConnectorType: mongodb
      mongodb:
        name: free5gc
        url: mongodb://mongodb:27017       
      
      nrfUri: http://nrf-nnrf:8000
      nrfCertPem: cert/nrf.pem

    logger:
      enable: true
      level: info
      reportCaller: false
