---
apiVersion: v1
kind: Service
metadata:
  name: udr-nudr
  labels:
    app.kubernetes.io/version: "v4.0.1"
    project: free5gc
    nf: udr
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    project: free5gc
    nf: udr
